version: "3"
services:
  cloud_redis:
    image: redis
    container_name: cloud_redis
  cloud:
    image: yangzxi/cloud:latest
    container_name: cloud
    ports:
      - "8999:8999"
    volumes:
      - ./data:/app/.data
    environment:
      - REDIS_HOST=cloud_redis
    restart: unless-stopped
    depends_on:
      - cloud_redis