version: "3"
services:
  cloud:
    image: yangzxin/cloud:latest
    container_name: cloud
    ports:
      - "8080:8999"
    volumes:
      - $PWD/data:/app/data
    environment:
      - TZ=Asia/shanghai
      - GUEST_PWD=123123
      - REDIS_HOST=cloud_redis
    # restart: unless-stopped
    restart: always