version: "3"
services:
  redis:
    image: redis
    container_name: cloud_redis
    # ports:
      # - "6378:6379"
  cloud:
    image: openjdk:17-jdk
    container_name: cloud
    ports:
      - "8080:8999"
    # command: bash -c "java '-Dloader.path=/home/cloud/lib' -jar /home/cloud/cloud-core-1.0.jar"
    command: bash -c "java -jar /home/cloud/cloud-core-1.0.jar"
    volumes:
      - $PWD:/home/cloud
    environment:
      - TZ=Asia/shanghai
      - GUEST_PWD=123123 #optional
      - REDIS_HOST=cloud_redis
    # restart: unless-stopped
    restart: always
    depends_on:
      - cloud_redis
networks:
  default:
    driver: cloud_net