server:
  port: 8999
spring:
  #数据库连接配置
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${user.dir}/cloud.db
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: 6379
  web:
    resources:
      # 静态资源地址，多个以逗号分割
      static-locations: classpath:/static/,file:./public/

  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 65MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  main:
    allow-circular-references: true

# 使用 mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: cn.xiaosm.cloud.**.entity
  # 支持统配符 * 或者 ; 分割
  type-enums-package: cn.xiaosm.cloud.**.entity.enums
  configuration:
    # 下划线转驼峰命名
    map-underscore-to-camel-case: true

management:
  health:
    mail:
      enabled: false # 启动时关闭邮箱检测

logging:
  level:
    cn.xiaosm.cloud.mapper: info

## 项目自定义配置
cloud:
  # 腾讯云配置
  tencent:
    secret-id:
    secret-key:
    bucket:
    domain:
    cdn-key:
  # max-upload-size: 120
  # local-path: ./storage/