server:
  port: 8999
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/cloud?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123123}
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  web:
    resources:
      # 静态资源地址，多个以逗号分割
      static-locations: file:./public/

  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 65MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  main:
    allow-circular-references: true

# 使用 mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: cn.xiaosm.cloud.**.entity
  # 支持统配符 * 或者 ; 分割
  type-enums-package: cn.xiaosm.cloud.**.entity.enums
  configuration:
    # 下划线转驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  health:
    mail:
      enabled: false # 启动时关闭邮箱检测

logging:
  #  config: classpath:log4j.properties
  level:
    cn.xiaosm.cloud.mapper: debug

## 项目自定义配置
cloud:
  local-path: ~/.cloud/
  max-upload-size: 120
  # 腾讯云配置
  tencent:
    secret-id:
    secret-key:
    bucket:
    domain:
    cdn-key: