server:
  port: 8999
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/cloud?${MYSQL_PARAMS:characterEncoding=utf-8}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:123456}
    # 连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,wall
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000 # 连

  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 65MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-circular-references: true

# 使用 mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: cn.xiaosm.cloud.**.entity
  # 支持统配符 * 或者 ; 分割
  type-enums-package: cn.xiaosm.cloud.**.entity.enums
  configuration:
    # 下划线转驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  #  config: classpath:log4j.properties
  level:
    cn.xiaosm.cloud.mapper: debug

## 项目自定义配置
cloud:
  local-path: ~/.cloud/local/
  chunk-path: ~/.cloud/chunk/
  max-upload-size: 120