server:
  port: 8080
spring:
  ycloud:
    local-path: C:\Users\Young\Desktop\local\
    chunk-path: C:\Users\Young\Desktop\chunk\
    max-upload-size: 120MB
  file-storage: #文件存储配置
    default-platform: local #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    local: # 本地存储（不推荐使用），不使用的情况下可以不写
      - platform: local # 存储平台标识
        enable-storage: true  #启用存储
        enable-access: false #启用访问（线上请使用 Nginx 配置，效率更高）
        domain: "" # 访问域名，例如：“http://127.0.0.1:8030/test/file/”，注意后面要和 path-patterns 保持一致，“/”结尾，本地存储建议使用相对路径，方便后期更换域名
        base-path: C:\Users\Young\Desktop\local\ # 存储地址
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ycloud?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123123
    # 连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    druid:
      filters: stat,wall
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 172.24.23.183
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000 # 连
  resources:
  # 静态资源地址，多个以逗号分割
  # static-locations: classpath:static/,file:static/

  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 65MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 使用 mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: cn.xiaosm.cloud.**.entity
  # 支持统配符 * 或者 ; 分割
  type-enums-package: cn.xiaosm.cloud.**.entity.enums
  configuration:
    # 下划线转驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  #  config: classpath:log4j.properties
  level:
    cn.xiaosm.cloud.mapper: debug

cloud:
  da: ABC